sudo: true
language: cpp

compiler:
  - clang
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL

install:
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-i386.tar.gz
      && tar -xzf cmake-3.2.3-Linux-i386.tar.gz
      && sudo cp -fR cmake-3.2.3-Linux-i386/* /usr

script: cmake CMakeLists.txt && make && ./bin/Debug/imn_exe


