sudo: false
language: cpp

compiler:
  - clang
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get update && sudo apt-get install -y llvm-3.4 llvm-3.4-dev; fi
  - rvm use $RVM --install --binary --fuzzy
  - gem update --system
  - gem --version

script: cmake CMakeLists.txt && make && ./bin/Debug/imn_exe


